config/routes.rb
Rails.application.routes.draw do
  resources :config_files
  resources :file_sets
  resources :sessions
  resources :users
  resources :results, :only => [ :update, :destroy ]
  resources :unmatched_files, :only => [ :create, :destroy ]
  resources :successful_files, :only => [ :create, :destroy ]
  resources :unsuccessful_files, :only => [ :create, :destroy ]
  resources :diffs do
    member do
      get :run
    end
  end

  match "/signout" => "sessions#destroy", via: [:get, :post], as: :signout
  match "/signin" => "sessions#new", via: [:get, :post], as: :signin
  match "/adauth" => "sessions#create", via: [:get, :post]

  root "diffs#index"
  get '/home' => "diffs#index"
  get '/fetch_result' => "diffs#from_result_id", as: 'fetch_result'

  get ':controller(/:action(/:id(.:format)))'

end

app/models/diff.rb
class Diff < ActiveRecord::Base
  validates_presence_of :title, :left_id, :right_id, :config_file_id
  validates_uniqueness_of :title
  validate :diff_file_sets

  has_many :results, :dependent => :destroy
  belongs_to :config_file
  belongs_to :left_file_set, :class_name => 'FileSet', :foreign_key => 'left_id'
  belongs_to :right_file_set, :class_name => 'FileSet', :foreign_key => 'right_id'

  # default_scope lambda { order('updated_at desc') }

  def diff_file_sets
    if self.left_id == self.right_id
      errors.add(:left_id, 'cannot use the same file set for both left and right')
      errors.add(:right, 'cannot use the same file set for both left and right')
    end
  end

  ransacker :title_case_insensitive, type: :string do
    arel_table[:title].lower
  end

end

app/controllers/diffs_controller.rb
class DiffsController < ApplicationController

  before_action :set_diff, only: [:run, :show, :edit, :update, :destroy]
  before_action :set_config_files, only: [:show, :edit, :update, :destroy]
  before_action :set_file_sets, only: [:show, :edit, :update, :destroy]
  after_action :add_action, only: [:run, :create, :edit, :update, :destroy]

  # GET /diffs
  # GET /diffs.json
  # TODO clean up diff/results query
  def index
    if params[:q].to_s.include? 'results_updated_at desc'
      @q = Diff.joins('LEFT OUTER JOIN `results` ON `results`.`diff_id` = `diffs`.`id` AND (results.id in (select a.id from (select id,diff_id from results order by id desc)  a group by a.diff_id))').order("results.updated_at desc").search()
    elsif params[:q].to_s.include? 'results_updated_at asc'
      @q = Diff.joins('LEFT OUTER JOIN `results` ON `results`.`diff_id` = `diffs`.`id` AND (results.id in (select a.id from (select id,diff_id from results order by id desc)  a group by a.diff_id))').order("results.updated_at asc").search()
    else
      @q = Diff.joins('LEFT OUTER JOIN `results` ON `results`.`diff_id` = `diffs`.`id` AND (results.id in (select a.id from (select id,diff_id from results order by id desc)  a group by a.diff_id))').search(params[:q])
    end
    @diffs = @q.result.includes(:config_file, :left_file_set, :right_file_set, :results)
    @q = Diff.search(params[:q])
  end

  # GET /diffs/1
  # GET /diffs/1.json
  def show
    @q = Result.where_diff_id(@diff.id).search(params[:q])
    @working_results = @q.result
    respond_to do |format|
      format.js {}
      format.html {}
    end
  end

  def from_result_id
    @result = Result.find(params[:result_id])
    @unmatched_left = UnmatchedFile.where_result_id_and_side(@result.id,'left').order('name ASC')
    @unmatched_right = UnmatchedFile.where_result_id_and_side(@result.id,'right').order('name ASC')
    @successful = SuccessfulFile.where_result_id(@result.id).order('left_name ASC')
    @unsuccessful = UnsuccessfulFile.where_result_id(@result.id).order('compare_key,id ASC')
    @unsuccessful_count = UnsuccessfulFile.where_result_id(@result.id).group('compare_key')
    respond_to do |format|
      format.js {}
    end
  end

  # GET /diffs/new
  def new
    @diff = Diff.new
  end

  # GET /diffs/1/edit
  def edit
    session[:return_to] = request.referer
  end

  def run
    @working_result=Result.new(:diff_id => @diff.id, :is_active => true, :pct_complete => 0)
    @working_result.save
    `(./bin/regression_diff.pl --result_id #{@working_result.id} --config_file #{@diff.config_file.cf.path} --left_zip #{@diff.left_file_set.fs.path} --right_zip #{@diff.right_file_set.fs.path} --output_prefix #{@current_user.login} 2>&1 | logger -t regression) > /dev/null 2>&1 &`
    # `(./bin/regression_diff.pl --result_id #{@working_result.id} --config_file #{@diff.config_file.cf.path} --left_zip #{@diff.left_file_set.fs.path} --right_zip #{@diff.right_file_set.fs.path} --output_prefix #{@current_user.login} > /tmp/regression.log 2>&1) > /dev/null 2>&1 &`
    sleep 2
    respond_to do |format|
      # format.html { redirect_to show_diff_path, status: :ok, location: @diff, notice: 'run was called.' }
      format.html { redirect_to @diff, notice: @working_result.id }
      format.json { head :no_content }
    end
  end

  # POST /diffs
  # POST /diffs.json
  def create
    @diff = Diff.new(diff_params)
    @diff.is_active = true

    respond_to do |format|
      if @diff.save
        format.html { redirect_to((session.delete(:return_to) || @diff), notice: 'Diff was successfully created.') }
        format.json { render :show, status: :created, location: @diff }
      else
        format.html { render :new }
        format.json { render json: @diff.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /diffs/1
  # PATCH/PUT /diffs/1.json
  def update
    respond_to do |format|
      if @diff.update(diff_params)
        format.html { redirect_to((session.delete(:return_to) || @diff), notice: 'Diff was successfully updated.') }
        format.json { render :show, status: :ok, location: @diff }
      else
        format.html { render :edit }
        format.json { render json: @diff.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /diffs/1
  # DELETE /diffs/1.json
  def destroy
    @diff.destroy
    # @diff.update(is_active: false)
    respond_to do |format|
      format.html { redirect_to diffs_url, notice: 'Diff was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_diff
    @diff = Diff.find(params[:id])
  end

  def set_config_files
    @config_files = ConfigFile.all
  end

  def set_file_sets
    @file_sets = FileSet.all
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def diff_params
    params.require(:diff).permit(:title, :description, :config_file_id, :left_id, :right_id)
  end

  def add_action
    Action.create(:action => action_name, :item => 'diff', :user_id => @current_user.id, :item_id => @diff.id)
  end

end

app/helpers/diffs_helper.rb
module DiffsHelper
end

app/views/diffs/_form.html.erb
<%= simple_form_for @diff, html: { class: 'form-horizontal', :multipart => true },
  wrapper: :horizontal_form do |f| %>
  <div class="col-md-6">
      <%= f.error_notification %>

      <div class="form-inputs">
        <%= f.input :title, placeholder: 'Title'  %>
        <%= f.input :description, placeholder: 'Description'  %>
        <%= f.association :config_file, label: 'Config File' %>
        <%= f.association :left_file_set, label: 'Left File Set' %>
        <%= f.association :right_file_set, label: 'Right File Set' %>
      </div>

      <div class="form-actions">
        <%= f.button :submit, {:class=>"btn btn-primary"} %>
        <%= link_to "Back", :back, {:class=>"btn btn-default btn-warning"} %>
      </div>
  </div>
<% end %>

app/views/diffs/_out_result.html.erb
<div class="row">
    <% if @unsuccessful.length > 0 %>
      <a href="#" class="btn btn-danger"
         data-toggle="modal" data-target="#unsuccessModal">Unsuccessful Files - <%= @unsuccessful_count.length %></a>
    <% else %>
      <a href="#" class="btn btn-default">Unsuccessful Files - <%= @unsuccessful_count.length %></a>
    <% end %>
    <div class="modal fade" id="unsuccessModal" tabindex="-1" role="dialog" aria-labelledby="unsuccessModal" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="btn btn-xs btn-default pull-right" data-dismiss="modal" aria-hidden="true">Close</button>
                    <h4 class="modal-title" id="unsuccessFiles">Unsuccessful Files - <%= @unsuccessful.group(:compare_key).length %></h4>
                </div>
                <div class="modal-body" style="white-space:nowrap;">
                    <% @unsuccessful.where(:right_line_number => '-1', :left_line_number => '-1').each do |compare_set| %>
                      <% if @unsuccessful.where_compare_key_and_not_line_zero(compare_set.compare_key).length > 0 %>
                        Left File: <a href=<%= compare_set.left_line.split('|==|').last %> ><%= compare_set.left_line.split('|==|').first %></a><br>
                        Right File: <a href=<%= compare_set.right_line.split('|==|').last %> ><%= compare_set.right_line.split('|==|').first %></a><br>
                        Useful: <%= compare_set.useful %>
                        <table class="table table-bordered table-striped">
                            <thead>
                            <tr>
                                <th>Line</th>
                                <th>
                                    Left Side<br>
                                    Right side
                                </th>
                            </tr>
                            </thead>

                            <tbody>
                            <% @unsuccessful.where_compare_key_and_not_line_zero(compare_set.compare_key).each do |line| %>
                              <tr style="font-family:monospace;">
                                  <td>
                                      <%= line.left_line_number.equal?(0) ? '-' : line.left_line_number %><br>
                                      <%= line.right_line_number.equal?(0) ? '-' : line.right_line_number %>
                                  </td>
                                  <td width="800" height="40">
                                      <div style="width:800px; height:60px; overflow-x:auto; overflow-y:fixed; white-space:nowrap;">
                                          <%= line.left_line %><br>
                                          <%= line.right_line %>
                                      </div>
                                  </td>
                              </tr>
                            <% end %>
                            </tbody>
                        </table>
                      <% end %>
                    <% end %>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-xs btn-default pull-right" data-dismiss="modal" aria-hidden="true">Close</button>
                </div>
            </div>
        </div>
    </div>
    <% if unmatched_left.length > 0 %>
      <a href="#" class="btn btn-warning"
         data-toggle="modal" data-target="#leftModal">Unmatched Files - Left - <%= unmatched_left.length %>/<%= result.left_count %></a>
    <% else %>
      <a href="#" class="btn btn-default">Unmatched Files - Left - <%= unmatched_left.length %>/<%= result.left_count %></a>
    <% end %>
    <div class="modal fade" id="leftModal" tabindex="-1" role="dialog" aria-labelledby="leftModal" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="btn btn-xs btn-default pull-right" data-dismiss="modal" aria-hidden="true">Close</button>
                    <h4 class="modal-title" id="unmatchedLeft">Unmatched Files - Left - <%= unmatched_left.length %>/<%= result.left_count %></h4>
                </div>
                <div class="modal-body">
                    <% unmatched_left.each do |file| %>
                      <a href=<%= file.url %> ><%= file.name %></a><br>
                    <% end %>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-xs btn-default pull-right" data-dismiss="modal" aria-hidden="true">Close</button>
                </div>
            </div>
        </div>
    </div>
    <% if unmatched_right.length > 0 %>
      <a href="#" class="btn btn-warning"
         data-toggle="modal" data-target="#rightModal">Unmatched Files - Right - <%= unmatched_right.length %>/<%= result.right_count %></a>
    <% else %>
      <a href="#" class="btn btn-default">Unmatched Files - Right - <%= unmatched_right.length %>/<%= result.right_count %></a>
    <% end %>
    <div class="modal fade" id="rightModal" tabindex="-1" role="dialog" aria-labelledby="rightModal" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="btn btn-xs btn-default pull-right" data-dismiss="modal" aria-hidden="true">Close</button>
                    <h4 class="modal-title" id="unmatchedRight">Unmatched Files - Right - <%= unmatched_right.length %>/<%= result.right_count %></h4>
                </div>
                <div class="modal-body">
                    <% unmatched_right.each do |file| %>
                      <a href=<%= file.url %> ><%= file.name %></a><br>
                    <% end %>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-xs btn-default pull-right" data-dismiss="modal" aria-hidden="true">Close</button>
                </div>
            </div>
        </div>
    </div>
    <% if successful.length > 0 %>
      <a href="#" class="btn btn-success"
         data-toggle="modal" data-target="#successModal">Successful Files - <%= successful.length %></a>
    <% else %>
      <a href="#" class="btn btn-default">Successful Files - <%= successful.length %></a>
    <% end %>
    <div class="modal fade" id="successModal" tabindex="-1" role="dialog" aria-labelledby="successModal" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="btn btn-xs btn-default pull-right" data-dismiss="modal" aria-hidden="true">Close</button>
                    <h4 class="modal-title" id="successFiles">Successful Files - <%= successful.length %></h4>
                </div>
                <div class="modal-body">
                    <table class="table table-bordered table-striped table-hover">
                        <thead>
                        <tr>
                            <th>Left Files</th>
                            <th>Right Files</th>
                        </tr>
                        </thead>

                        <tbody>
                        <% successful.each do |file| %>
                          <tr>
                              <td><%= file.left_name %></td>
                              <td><%= file.right_name %></td>
                          </tr>
                        <% end %>
                        </tbody>
                    </table>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-xs btn-default pull-right" data-dismiss="modal" aria-hidden="true">Close</button>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/diffs/edit.html.erb
<%= render 'form' %>

app/views/diffs/from_result_id.js.erb
$("#out_result").html("<%= escape_javascript(render partial: 'out_result', locals: { unmatched_left: @unmatched_left, unmatched_right: @unmatched_right, successful: @successful, unsuccessful: @unsuccessful, result: @result } ) %>"); //load html from the url and put it in the #content element

app/views/diffs/index.html.erb
<div class='row'>
    <p id="notice"><%= @notice %></p>
    <div class='col-xs-6'>
        <%= link_to 'New Diff', new_diff_path, class: 'btn btn-xs btn-primary nounderline'  %>
    </div>
    <div class='col-xs-6 text-right'>
        <%= search_form_for @q do |f| %>
          <%= f.search_field :title_or_description_or_config_file_name_or_right_file_set_name_or_left_file_set_name_cont %>

          <%= f.submit 'Search', {:class=>"btn btn-xs btn-primary"} %>
        <% end %>
    </div>
</div>
<!-- TODO filter links for mine, all, recent, etc -->
<!-- TODO pagination -->
<div class='row'>
    <table class="table table-bordered table-striped table-hover">
        <thead>
        <tr>
            <th><%= sort_link(@q,:title_case_insensitive, 'Title')%></th>
            <th>
                C: <%= sort_link(@q,:config_file_name,'Config File')%><br>
                L: <%= sort_link(@q,:left_file_set_name,'Left File Set')%><br>
                R: <%= sort_link(@q,:right_file_set_name,'Right File Set')%>
            </th>
            <th><%= sort_link(@q,:results_updated_at,'Last Result', default_order: :desc) %></th>
            <th></th>
        </tr>
        </thead>

        <tbody>
        <% @diffs.each do |diff| %>
          <tr data-link="row" class='rowlink'>
              <td><%= link_to diff.title, diff %><br>
                  <div class="bs-component">
                      <% if diff.description.empty? %>
                        <button title="" data-original-title="" type="button" class="btn btn-xs btn-default rowlink-skip" data-container="body" data-toggle="popover" data-placement="right" data-content="<%= diff.description %>">
                            No Description
                        </button>
                      <% else %>
                        <button title="" data-original-title="" type="button" class="btn btn-xs btn-primary rowlink-skip" data-container="body" data-toggle="popover" data-placement="right" data-content="<%= diff.description %>">
                            Click For Description
                        </button>
                      <% end %>
                  </div>
              </td>
              <td>
                  C: <%= link_to diff.config_file.name, config_file_path(diff.config_file), class: 'rowlink-skip underline' %><br>
                  L: <%= link_to diff.left_file_set.name, file_set_path(diff.left_file_set), class: 'rowlink-skip underline' %><br>
                  R: <%= link_to diff.right_file_set.name, file_set_path(diff.right_file_set), class: 'rowlink-skip underline' %>
              </td>
              <td>
                  <% if diff.results.first.nil? %>
                    &nbsp;
                  <% else %>
                    <%= diff.results.first.updated_at.localtime.strftime("%F %T %Z") %>
                    (<%= diff.results.first.pct_complete %>%)
                  <% end %>
              </td>
              <td class="rowlink-skip"><%= link_to 'Destroy', diff, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-danger nounderline' %></td>
          </tr>
        <% end %>
        </tbody>
    </table>
</div>
<div class='row'>
    <%= link_to 'New Diff', new_diff_path, class: 'btn btn-xs btn-primary nounderline'  %>
</div>
<script>
  (function(){
    $('.bs-component [data-toggle="popover"]').popover();
    $('.bs-component [data-toggle="tooltip"]').tooltip();
  })();
</script>

app/views/diffs/new.html.erb
<h1>New diff</h1>

<%= render 'form' %>

app/views/diffs/show.html.erb
<div class="container-fluid">
    <div class="row">
        <div class="col-md-6">
            <%= simple_form_for @diff, html: { class: 'form-horizontal', :multipart => true }, wrapper: :horizontal_form do |f| %>

              <div class="form-inputs">
                  <%= f.input :title, placeholder: 'Title', disabled: true  %>
                  <%= f.input :description, placeholder: 'Description', disabled: true  %>
                  <%= f.association :config_file, label: 'Config File', disabled: true  %>
                  <%= f.association :left_file_set, label: 'Left File Set', disabled: true  %>
                  <div class="form-group string optional diff_right_file_set">
                      <%= f.label :right_file_set, "Right File Set", class: 'string optional col-sm-3 control-label' %>
                      <div class="col-sm-9">
                          <div class="input-group">
                              <%= f.input_field :right_file_set, disabled: true, class: 'string optional form-control', value: @diff.right_file_set.name %>
                              <span class="input-group-btn">
                                  <%= link_to 'Update Zip', edit_file_set_path(@diff.right_file_set.id), class: 'btn btn-primary' %>
                              </span>
                          </div>
                      </div>
                  </div>
              </div>

              <div class="form-actions">
                  <%= link_to "Run", run_diff_path(@diff), class: 'btn btn-success', data: { confirm: 'Are you sure you want this diff to start running?' } %>
                  <%= link_to "Edit", edit_diff_path(@diff), class: 'btn btn-primary' %>
              </div>
            <% end %>
        </div>

        <div class="col-md-4">
            <h2 class="sub-header">Results</h2>

            <table class="table table-bordered table-striped table-hover">
                <thead>
                <tr>
                    <th><%= sort_link(@q,:updated_at,'Last Update', default_order: :desc) %></th>
                    <th><%= sort_link(@q,:pct_complete,'% Complete')%></th>
                </tr>
                </thead>

                <!-- TODO Display files in new popup window -->
                <tbody>
                <% @working_results.each do |result| %>
                  <tr data-link="row" class="rowlink">
                      <td id="result_cell"><%= link_to result.updated_at.localtime.strftime("%F %T %Z"), fetch_result_path(:result_id => result.id), :remote => true %></td>
                      <td><%= result.pct_complete %></td>
                      <td class="rowlink-skip"><%= link_to "Destroy", result, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-danger nounderline' %></td>
                  </tr>
                <% end %>
                </tbody>
            </table>

        </div>
    </div>
    <hr>
    <div class="row">
        <div id="out_result" >
        </div>
    </div>
</div>