config/routes.rb
Rails.application.routes.draw do
  resources :config_files
  resources :file_sets
  resources :sessions
  resources :users
  resources :results, :only => [ :update, :destroy ]
  resources :unmatched_files, :only => [ :create, :destroy ]
  resources :successful_files, :only => [ :create, :destroy ]
  resources :unsuccessful_files, :only => [ :create, :destroy ]
  resources :diffs do
    member do
      get :run
    end
  end

  match "/signout" => "sessions#destroy", via: [:get, :post], as: :signout
  match "/signin" => "sessions#new", via: [:get, :post], as: :signin
  match "/adauth" => "sessions#create", via: [:get, :post]

  root "diffs#index"
  get '/home' => "diffs#index"
  get '/fetch_result' => "diffs#from_result_id", as: 'fetch_result'

  get ':controller(/:action(/:id(.:format)))'

end

app/models/config_file.rb
class ConfigFile < ActiveRecord::Base
  has_attached_file  :cf

  validates_presence_of :name
  validates_uniqueness_of :name
  validates_presence_of :cf
  validates_attachment_file_name :cf, :matches => [/txt\Z/, /yml\Z/]

  before_create :randomize_file_name

  has_many :diffs, :dependent => :restrict_with_error

  # default_scope lambda { where("config_files.is_active = 1") }
  ransacker :name_case_insensitive, type: :string do
    arel_table[:name].lower
  end

  private

  def randomize_file_name
    extension = File.extname(cf_file_name).downcase
    self.cf.instance_write(:file_name, "#{SecureRandom.hex(16)}#{extension}")
  end

end

app/controllers/config_files_controller.rb
class ConfigFilesController < ApplicationController
  before_action :set_config_file, only: [:show, :edit, :update, :destroy]
  after_action :add_action, only: [:create, :edit, :update, :destroy]

  # GET /config_files
  # GET /config_files.json
  def index
    @q = ConfigFile.search(params[:q])
    @config_files = @q.result.includes(:diffs)
  end

  # GET /config_files/1
  # GET /config_files/1.json
  def show
  end

  # GET /config_files/new
  def new
    @config_file = ConfigFile.new
  end

  # GET /config_files/1/edit
  def edit
    session[:return_to] = request.referer
  end

  # POST /config_files
  # POST /config_files.json
  def create
    @config_file = ConfigFile.new(config_file_params)
    @config_file.is_active = true

    respond_to do |format|
      if @config_file.save
        format.html { redirect_to((session.delete(:return_to) || @config_file), notice: 'Config file was successfully created.') }
        format.json { render :show, status: :created, location: @config_file }
      else
        format.html { render :new }
        format.json { render json: @config_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /config_files/1
  # PATCH/PUT /config_files/1.json
  def update
    respond_to do |format|
      if @config_file.update(config_file_params)
        format.html { redirect_to((session.delete(:return_to) || @config_file), notice: 'Config file was successfully updated.') }
        format.json { render :show, status: :ok, location: @config_file }
      else
        format.html { render :edit }
        format.json { render json: @config_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /config_files/1
  # DELETE /config_files/1.json
  def destroy
    @config_file.destroy
    # @config_file.update(is_active: false)

    respond_to do |format|
      format.html { redirect_to config_files_url, notice: 'Config file was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_config_file
      @config_file = ConfigFile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def config_file_params
      params.require(:config_file).permit(:name, :description, :cf)
    end

    def add_action
      Action.create(:action => action_name, :item => 'config_file', :user_id => @current_user.id, :item_id => @config_file.id)
    end
end

app/helpers/config_files_helper.rb
module ConfigFilesHelper
end

app/views/config_files/_form.html.erb
<%= simple_form_for @config_file, html: { class: 'form-horizontal', :multipart => true },
  wrapper: :horizontal_form, wrapper_mappings: { file: :horizontal_form_b } do |f| %>
  <div class="col-md-6">
      <%= f.error_notification %>

      <div class="form-inputs">
        <%= f.input :name, placeholder: 'Title'  %>
        <%= f.input :description, placeholder: 'Description'  %>

        <div class="form-group string optional disabled config_file_cf">
          <label class="string optional col-sm-3 control-label" for="config_file_cf">Config File</label>
          <div class="col-sm-9">
            <div class="input-group">
              <span class="input-group-btn">
                <span class="btn btn-primary btn-file">
                  Browse&hellip; <input  name="config_file[cf]" type="file">
                </span>
              </span>
              <input type="text" class="form-control" value="<%= @config_file.cf_file_name %>" readonly>
            </div>
          </div>
        </div>
      </div>

      <div class="form-actions">
        <%= f.button :submit, {:class=>"btn btn-default btn-primary"} %>
        <%= link_to "Back", :back, {:class=>"btn btn-default btn-warning"} %>
      </div>
  </div>
<% end %>

app/views/config_files/edit.html.erb
<p id="notice"><%= notice %></p>

<%= render 'form' %>

app/views/config_files/index.html.erb
<div class='row'>
    <p id="notice"><%= @notice %></p>
    <div class='col-xs-6'>
        <%= link_to 'New Config File', new_config_file_path, class: 'btn btn-xs btn-primary nounderline'  %>
    </div>
    <div class='col-xs-6 text-right'>
        <%= search_form_for @q do |f| %>
          <%= f.search_field :name_or_description_or_diffs_title_or_diffs_description_cont %>

          <%= f.submit 'Search', {:class=>"btn btn-xs btn-primary"} %>
        <% end %>
    </div>
</div>
<div class='row'>
    <table class="table table-bordered table-striped table-hover">
        <thead>
        <tr>
            <th><%= sort_link(@q,:name, 'Name')%></th>
            <th><%= sort_link(@q,'cf_file_name','Config File Name')%></th>
            <th><%= sort_link(@q,:updated_at,'Last Updated')%></th>
            <th>Used in Diff</th>
            <th></th>
        </tr>
        </thead>

        <tbody>
        <% @config_files.each do |config_file| %>
          <tr data-link="row" class="rowlink">
              <td><%= link_to config_file.name, config_file %><br>
                  <div class="bs-component">
                      <% if config_file.description.empty? %>
                        <button title="" data-original-title="" type="button" class="btn btn-xs btn-default rowlink-skip" data-container="body" data-toggle="popover" data-placement="right" data-content="<%= config_file.description %>">
                            No Description
                        </button>
                      <% else %>
                        <button title="" data-original-title="" type="button" class="btn btn-xs btn-primary rowlink-skip" data-container="body" data-toggle="popover" data-placement="right" data-content="<%= config_file.description %>">
                            Click For Description
                        </button>
                      <% end %>
                  </div>
              </td>
              <td><%= config_file.cf_file_name %></td>
              <td><%= config_file.updated_at.localtime.strftime("%F %T %Z") %></td>
              <td>
                  <% config_file.diffs.each do |diff| %>
                    <%= link_to diff.title, diff_path(diff), class: 'rowlink-skip underline'  %><br>
                  <% end %>
              </td>
              <td class="rowlink-skip">
                  <% if config_file.can_destroy? %>
                    <%= link_to 'Destroy', config_file, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-danger nounderline' %>
                  <% else %>
                    <%= link_to 'Destroy', config_file, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-default disabled nounderline' %>
                  <% end %>
              </td>
          </tr>
        <% end %>
        </tbody>
    </table>
</div>
<div class='row'>
    <%= link_to 'New Config File', new_config_file_path, class: 'btn btn-xs btn-primary nounderline'  %>
</div>
<script>
  (function(){
    $('.bs-component [data-toggle="popover"]').popover();
    $('.bs-component [data-toggle="tooltip"]').tooltip();
  })();
</script>

app/views/config_files/new.html.erb
<h1>New config_file</h1>

<%= render 'form' %>

app/views/config_files/show.html.erb
<%= simple_form_for @config_file, html: { class: 'form-horizontal', :multipart => true },
  wrapper: :horizontal_form do |f| %>
  <div class="col-md-6">
      <p id="notice"><%= notice %></p>

      <div class="form-inputs">
        <%= f.input :name, placeholder: 'Title', disabled: true  %>
        <%= f.input :description, placeholder: 'Description', disabled: true  %>
        <%= f.input :cf, as: :string, placeholder: 'Config File Name', label: 'Config File',
                input_html: { value: @config_file.cf_file_name }, disabled: true  %>

      </div>
      <!-- TODO Display config file contents -->
      <div class="form-actions">
        <%= link_to "Edit", edit_config_file_path(@config_file), {:class=>"btn btn-default btn-primary"} %>
        <%= link_to "Back", :back, {:class=>"btn btn-default btn-warning"} %>
      </div>
  </div>
<% end %>