config/routes.rb
Rails.application.routes.draw do
  resources :config_files
  resources :file_sets
  resources :sessions
  resources :users
  resources :results, :only => [ :update, :destroy ]
  resources :unmatched_files, :only => [ :create, :destroy ]
  resources :successful_files, :only => [ :create, :destroy ]
  resources :unsuccessful_files, :only => [ :create, :destroy ]
  resources :diffs do
    member do
      get :run
    end
  end

  match "/signout" => "sessions#destroy", via: [:get, :post], as: :signout
  match "/signin" => "sessions#new", via: [:get, :post], as: :signin
  match "/adauth" => "sessions#create", via: [:get, :post]

  root "diffs#index"
  get '/home' => "diffs#index"
  get '/fetch_result' => "diffs#from_result_id", as: 'fetch_result'

  get ':controller(/:action(/:id(.:format)))'

end

app/models/file_set.rb
class FileSet < ActiveRecord::Base
  has_attached_file  :fs

  validates_presence_of :name
  validates_uniqueness_of :name
  validates_presence_of :fs
  validates_attachment_file_name :fs, :matches => [/zip\Z/, /tgz\Z/]

  before_create :randomize_file_name


  has_many :diffs_left, :class_name => 'Diff', :foreign_key => 'left_id', :dependent => :restrict_with_error
  has_many :diffs_right, :class_name => 'Diff', :foreign_key => 'right_id', :dependent => :restrict_with_error

  # default_scope lambda { where("file_sets.is_active = 1") }

  ransacker :name_case_insensitive, type: :string do
    arel_table[:name].lower
  end

  private

  def randomize_file_name
    extension = File.extname(fs_file_name).downcase
    self.fs.instance_write(:file_name, "#{SecureRandom.hex(16)}#{extension}")
  end

end

app/controllers/file_sets_controller.rb
class FileSetsController < ApplicationController
  before_action :set_file_set, only: [:show, :edit, :update, :destroy]
  after_action :add_action, only: [:create, :edit, :update, :destroy]

  # GET /file_sets
  # GET /file_sets.json
  def index
    @q = FileSet.search(params[:q])
    @file_sets = @q.result.includes(:diffs_left, :diffs_right)
  end

  # GET /file_sets/1
  # GET /file_sets/1.json
  def show
  end

  # GET /file_sets/new
  def new
    @file_set = FileSet.new
  end

  # GET /file_sets/1/edit
  def edit
    session[:return_to] = request.referer
  end

  # POST /file_sets
  # POST /file_sets.json
  # TODO Quotas
  def create
    @file_set = FileSet.new(file_set_params)
    @file_set.is_active = true

    respond_to do |format|
      if @file_set.save
        format.html { redirect_to((session.delete(:return_to) || @file_set), notice: 'File set was successfully created.') }
        format.json { render :show, status: :created, location: @file_set }
      else
        format.html { render :new }
        format.json { render json: @file_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /file_sets/1
  # PATCH/PUT /file_sets/1.json
  def update
    respond_to do |format|
      if @file_set.update(file_set_params)
        format.html { redirect_to((session.delete(:return_to) || @file_set), notice: 'File set successfully updated.') }
        format.json { render :show, status: :ok, location: @file_set }
      else
        format.html { render :edit }
        format.json { render json: @file_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /file_sets/1
  # DELETE /file_sets/1.json
  def destroy
    @file_set.destroy
    # @file_set.update(is_active: false)

    respond_to do |format|
      format.html { redirect_to file_sets_url, notice: 'File set was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_file_set
      @file_set = FileSet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def file_set_params
      params.require(:file_set).permit(:name, :description, :fs)
    end

    def add_action
      Action.create(:action => action_name, :item => 'file_set', :user_id => @current_user.id, :item_id => @file_set.id)
    end
end

app/helpers/file_sets_helper.rb
module FileSetsHelper
end

app/views/file_sets/_form.html.erb
<%= simple_form_for @file_set, html: { class: 'form-horizontal', :multipart => true },
  wrapper: :horizontal_form do |f| %>
  <div class="col-md-6">
      <%= f.error_notification %>
<p id="notice"><%= @notice %></p>

      <div class="form-inputs">
        <%= f.input :name, placeholder: 'Title'  %>
        <%= f.input :description, placeholder: 'Description'  %>

        <div class="form-group string optional disabled file_set_fs">
          <label class="string optional col-sm-3 control-label" for="file_set_fs">File Set</label>
          <div class="col-sm-9">
            <div class="input-group">
              <span class="input-group-btn">
                <span class="btn btn-primary btn-file">
                  Browse&hellip; <input  name="file_set[fs]" type="file">
                </span>
              </span>
              <input type="text" class="form-control" value="<%= @file_set.fs_file_name %>" readonly>
            </div>
          </div>
        </div>
      </div>

      <div class="form-actions">
        <%= f.button :submit, {:class=>"btn btn-default btn-primary"} %>
        <%= link_to "Back", :back, {:class=>"btn btn-default btn-warning"} %>
      </div>
  </div>
<% end %>

app/views/file_sets/edit.html.erb
<p id="notice"><%= @notice %></p>

<%= render 'form' %>

app/views/file_sets/index.html.erb
<div class='row'>
    <p id="notice"><%= @notice %></p>
    <div class='col-xs-6'>
        <%= link_to 'New File Set', new_file_set_path, class: 'btn btn-xs btn-primary nounderline'  %>
    </div>
    <div class='col-xs-6 text-right'>
        <%= search_form_for @q do |f| %>
          <%= f.search_field :name_or_description_or_diffs_left_title_or_diffs_right_title_cont %>

          <%= f.submit 'Search', {:class=>"btn btn-xs btn-primary"} %>
        <% end %>
    </div>
</div>
<div class='row'>
    <table class="table table-bordered table-striped table-hover">
        <thead>
        <tr>
            <th><%= sort_link(@q,:name_case_insensitive, 'Name')%></th>
            <th>
                <%= sort_link(@q,:diffs_left_title,'L: Used as Left')%><br>
                <%= sort_link(@q,:diffs_right_title,'R: Used as Right')%>
            </th>
            <th><%= sort_link(@q,:updated_at,'Last Updated')%></th>
            <th></th>
        </tr>
        </thead>

        <tbody>
        <% @file_sets.each do |file_set| %>
          <tr data-link="row" class="rowlink">
              <td><%= link_to file_set.name, file_set %><br>
                  <div class="bs-component">
                      <% if file_set.description.empty? %>
                        <button title="" data-original-title="" type="button" class="btn btn-xs btn-default rowlink-skip" data-container="body" data-toggle="popover" data-placement="right" data-content="<%= file_set.description %>">
                            No Description
                        </button>
                      <% else %>
                        <button title="" data-original-title="" type="button" class="btn btn-xs btn-primary rowlink-skip" data-container="body" data-toggle="popover" data-placement="right" data-content="<%= file_set.description %>">
                            Click For Description
                        </button>
                      <% end %>
                  </div>
              </td>
              <td>
                  L: <% file_set.diffs_left.each do |diff| %>
                    <%= link_to diff.title, diff_path(diff), class: 'rowlink-skip underline' %>
                  <% end %><br>
                  R: <% file_set.diffs_right.each do |diff| %>
                    <%= link_to diff.title, diff_path(diff), class: 'rowlink-skip underline' %>
                  <% end %>
              </td>
              <td><%= file_set.updated_at.localtime.strftime("%F %T %Z") %></td>
              <td class="rowlink-skip">
                  <% if file_set.can_destroy? %>
                    <%= link_to 'Destroy', file_set, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-danger nounderline' %>
                  <% else %>
                    <%= link_to 'Destroy', file_set, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-default disabled nounderline' %>
                  <% end %>
              </td>
          </tr>
        <% end %>
        </tbody>
    </table>
</div>
<div class='row'>
    <%= link_to 'New File Set', new_file_set_path, class: 'btn btn-xs btn-primary nounderline'  %>
</div>
<script>
  (function(){
    $('.bs-component [data-toggle="popover"]').popover();
    $('.bs-component [data-toggle="tooltip"]').tooltip();
  })();
</script>

app/views/file_sets/new.html.erb
<h1>New file_set</h1>
<p id="notice"><%= @notice %></p>

<%= render 'form' %>

app/views/file_sets/show.html.erb
<%= simple_form_for @file_set, html: { class: 'form-horizontal', :multipart => true },
                    wrapper: :horizontal_form do |f| %>
  <div class="col-md-6">
      <p id="notice"><%= @notice %><%= notice %></p>

      <div class="form-inputs">
          <%= f.input :name, placeholder: 'Title', disabled: true  %>
          <%= f.input :description, placeholder: 'Description', disabled: true  %>
          <%= f.input :fs, as: :string, placeholder: 'File Set Name', label: 'File Set',
                      input_html: { value: @file_set.fs_file_name }, disabled: true  %>

      </div>
      <!-- TODO Display file_set contents - file list -->
      <div class="form-actions">
          <%= link_to "Edit", edit_file_set_path(@file_set), {:class=>"btn btn-default btn-primary"} %>
          <%= link_to "Back", :back, {:class=>"btn btn-default btn-warning"} %>
      </div>
  </div>
<% end %>